import { Button, VerticalBox ,AboutSlint, LineEdit} from "std-widgets.slint";


export component AppWindow inherits Window {
    in property <string> results:"";
    callback divide-income(string);
    background:#222831 ;
    GridLayout {
        
        padding: 50px;
        spacing: 25px;
        Row{
            Text{
                
                
                text:"Enter Total Income";
                horizontal-alignment: center;
                font-size: 24px;
                font-weight:900;
                color:#76ABAE;
                
            }
        }
        Row{
            income:=LineEdit {
                horizontal-alignment: center;
                font-size: 14px;
                placeholder-text: "Enter your number";
                height: 35px;

            }
        }
        Row{
            Button {
                text: "Calculate";
                primary: true;
                height: 35px;
                clicked => {divide-income(income.text)}

            }
        }
        Row{
            VerticalBox {
                Rectangle {
                    height: 100px;
                    background:#EEEEEE ;
                    Text {
                        color:black;
                        font-size: 16px;
                        font-weight: 500;
                        text: root.results;
                    }
                }
            }
        }
    }
    
    // in-out property<int> counter: 42;
    // callback request-increase-value();
    // VerticalBox {
    //     Text {
    //         text: "Counter: \{root.counter}";
    //     }
    //     Button {
    //         text: "Increase value";
    //         clicked => {
    //             root.request-increase-value();
    //         }
    //     }
    // }
}
